name: Python CI

on:
  push:
  pull_request:      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r hw/requirements.txt
          pip install --upgrade markupsafe
      - name: Run pytest
        run: pytest hw/tests/

      - name: Run mypy
        run: python -m mypy --python-version 3.11 --config-file=<(echo "[mypy-markupsafe._speedups]"; echo "ignore_errors = True") hw/

      - name: Run black
        run: black --diff --check hw/

      - name: Run isort
        run: isort --check-only --diff --profile black hw/

      - name: Run flake8
        run: flake8 hw/
