name: Python CI

on:
  push:
  pull_request:      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r hw/requirements.txt
          # pip install --upgrade markupsafe
          pip install "click<8.1.0" black
          # echo -e "[mypy]\npython_version = 3.11\n\n[mypy-markupsafe._speedups]\nignore_errors = True" > mypy_temp.ini
      - name: Run pytest
        run: pytest hw/tests/

      # - name: Run mypy
      #   run: python -m mypy --config-file mypy_temp.ini hw/

      - name: Run black
        run: black --diff --check hw/

      - name: Run isort
        run: isort --check-only --diff --profile black hw/

      - name: Run flake8
        run: flake8 hw/
